module.exports = {
  parserOptions: {
    ecmaVersion: 9,
    sourceType: 'module',
  },
  rules: {
    'prefer-const': 'error',
    'no-const-assign': 'error',
    'no-multi-assign': 'error',
    'no-var': 'error',
    'no-new-object': 'error',
    'object-shorthand': 'error',
    'quote-props': ['error', 'as-needed'],
    'no-array-constructor': 'error',
    'array-callback-return': 'error',
    'prefer-destructuring': ['error', { object: true, array: true }],
    quotes: ['error', 'single'],
    'template-curly-spacing': 'error',
    'wrap-iife': 'error',
    'prefer-rest-params': 'error',
    'no-param-reassign': 'error',
    'prefer-spread': 'error',
    'no-plusplus': 'error',
    'nonblock-statement-body-position': ['error', 'beside'],
    'brace-style': 'error',
    'spaced-comment': 'error',
    indent: ['error', 2],
    'space-before-blocks': 'error',
    'padded-blocks': ['error', 'never'],
    'space-in-parens': ['error', 'never'],
    'comma-style': ['error', 'last'],
    'comma-dangle': ['error', 'only-multiline'],
    semi: 'error',
  },
  env: {
    es6: true,
    browser: true,
    node: true,
  },
  extends: ['eslint:recommended'],
  parserOptions: {
    ecmaVersion: 9,
    sourceType: 'module',
  },
  plugins: ['svelte3'],
  overrides: [
    {
      files: ['*.svelte'],
      processor: 'svelte3/svelte3',
      settings: {
        'svelte3/ignore-styles': () => true,
      },
    },
  ],
};
